/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as EmprestimoRouteImport } from './routes/emprestimo'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprestimoRoute = EmprestimoRouteImport.update({
  id: '/emprestimo',
  path: '/emprestimo',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/emprestimo': typeof EmprestimoRoute
  '/investimentos': typeof InvestimentosRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/emprestimo': typeof EmprestimoRoute
  '/investimentos': typeof InvestimentosRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/emprestimo': typeof EmprestimoRoute
  '/investimentos': typeof InvestimentosRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/planejamento': typeof PlanejamentoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartoes'
    | '/emprestimo'
    | '/investimentos'
    | '/lancamentos'
    | '/login'
    | '/planejamento'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartoes'
    | '/emprestimo'
    | '/investimentos'
    | '/lancamentos'
    | '/login'
    | '/planejamento'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cartoes'
    | '/emprestimo'
    | '/investimentos'
    | '/lancamentos'
    | '/login'
    | '/planejamento'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartoesRoute: typeof CartoesRoute
  EmprestimoRoute: typeof EmprestimoRoute
  InvestimentosRoute: typeof InvestimentosRoute
  LancamentosRoute: typeof LancamentosRoute
  LoginRoute: typeof LoginRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprestimo': {
      id: '/emprestimo'
      path: '/emprestimo'
      fullPath: '/emprestimo'
      preLoaderRoute: typeof EmprestimoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartoesRoute: CartoesRoute,
  EmprestimoRoute: EmprestimoRoute,
  InvestimentosRoute: InvestimentosRoute,
  LancamentosRoute: LancamentosRoute,
  LoginRoute: LoginRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
